services:
  server:
    build:
      context: ./bookture_server
      dockerfile: Dockerfile
    env_file:
      - ./bookture_server/.env
    ports:
      - "7000:7000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookture-network
    volumes:
      - ./bookture_server/uploads:/app/uploads

  db:
    build: ./bookture_db
    container_name: bookture_db
    restart: always
    environment:
      POSTGRES_USER: bookture
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: bookture
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bookture-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookture -d bookture"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bookture-network:
    driver: bridge

volumes:
  db_data:
